{{- range $key, $val := $.Values.apps.cephfs.appsname }}
{{- if $.Values.apps.cephfs.enabled }}
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ $val }}
  labels:
    app: {{ $val }}
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
{{- if $.Values.s2i.enabled }}
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - cephfsworkloadgenerator
        from:
          kind: ImageStreamTag
          name: '{{ $.Values.s2i.isname }}:latest'
{{- end }}
  replicas: 1
  revisionHistoryLimit: 5
  test: false
  selector:
    app: {{ $val }}
    deploymentconfig: {{ $val }}
  template:
    metadata:
      labels:
        app: {{ $val }}
        deploymentconfig: {{ $val }}
    spec:
      topologySpreadConstraints:
      - labelSelector:
           matchLabels: 
               deploymentconfig: {{ $val }}
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      - labelSelector:
           matchLabels: 
               deploymentconfig: {{ $val }}
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      containers:
{{- if $.Values.s2i.enabled }}
      - image: '{{ $.Values.s2i.isname }}'
{{ else }}
      - image: '{{ $.Values.s2i.image }}'
{{- end }}
        imagePullPolicy: Always
        name: cephfsworkloadgenerator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: CEPH_PV_MOUNT_DIR
          value: '{{ $.Values.apps.cephfs.mountpoint }}'
        - name: CEPH_TEST_COMP
          value: fs
        - name: CEPH_TEST_TYPE
{{- if or (eq $val "cephfs-write-workload-generator-cache") (eq $val "cephfs-write-workload-generator-no-cache") }}
          value: write
{{- end }}
{{- if or (eq $val "cephfs-read-workload-generator-cache") (eq $val "cephfs-read-workload-generator-no-cache") }}
          value: read
{{- end }}
        - name: CEPH_TEST_W_CACHE
{{- if or (eq $val "cephfs-write-workload-generator-cache") (eq $val "cephfs-read-workload-generator-cache") }}
          value: 'yes'
{{- end }}
{{- if or (eq $val "cephfs-write-workload-generator-no-cache") (eq $val "cephfs-read-workload-generator-no-cache") }}
          value: 'no'
{{- end }}
        - name: CEPH_TEST_SLEEP
          value: '0.1'
        volumeMounts:
        - name: {{ $val }}-persistent-storage
          mountPath: /mnt/pv
      volumes:
      - name: {{ $val }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ $val }}-pv-claim
{{- end }}
{{- end }}
