{{- range $key, $val := $.Values.apps.s3.appsname }}
{{- if $.Values.apps.s3.enabled }}
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ $val }}-{{ $.Release.Namespace | trunc 5 }}
spec:
  generateBucketName: {{ $val | substr 13 27 }}
  storageClassName: '{{ $.Values.apps.s3.sc }}'
{{- end }}
{{- end }}
