{{- range $key, $val := $.Values.argocd }}
{{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
spec:
  destination:
    name: ''
    namespace: '{{ $val.namespace }}'
    server: 'https://kubernetes.default.svc'
  source:
    path: '{{ $val.path }}'
    repoURL: '{{ $.Values.helmRepoUrl }}'
    targetRevision: '{{ $val.branch }}'
  project: '{{ $val.project }}'
{{- if $val.autosync }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false  
{{- end }}
  ignoreDifferences:
  - group: DeploymentConfig.openshift.io
    kind: DeploymentConfig
    jsonPointers:
      - /spec/template/spec/containers/image
{{- end }}
{{- end }}
